---
- hosts: dev-python
  user: vagrant

  vars:
    python_version: 3.5.0

  tasks:
  - name: install basic pkg
    apt: name={{item}} state=installed
    sudo: yes
    with_items:
    - vim
    - git
    - rsync
    - zsh

  - name: install build python package
    sudo: yes
    apt: name={{item}} state=installed
    with_items:
    - gcc
    - make
    - openssl
    - libssl-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev

  - name: install pyenv
    args:
      creates: ~/.pyenv
    shell: |
      git clone https://github.com/yyuu/pyenv.git ~/.pyenv
      ## add pyenv env
      (
          echo 'export PYENV_ROOT=~/.pyenv'
          echo 'export PATH=$PYENV_ROOT/bin:$PATH'
          echo 'eval "$(pyenv init -)"'
      ) >> ~/.zshrc
      source ~/.zshrc
      (
          echo 'export PYENV_ROOT=~/.pyenv'
          echo 'export PATH=$PYENV_ROOT/bin:$PATH'
          echo 'eval "$(pyenv init -)"'
      ) >> ~/.bashrc
      source ~/.bashrc
      # install python
      pyenv install {{python_version}}
      pyenv rehash
      pyenv global {{python_version}}

  - name: install pip
    sudo: yes
    shell: |
      zsh
      wget https://bootstrap.pypa.io/get-pip.py
      python get-pip.py

  - name: pip install pkgs
    pip: name={{item}}
    with_items:
    - flask
    - lxml
    - uwsgi
